---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.3.9-jdk-8

inputs:
- name: java-service

outputs:
- name: artifacts

caches:
  - path: .m2/

run:
  path: ci/build.sh
  dir: java-service
